---

- name: Services
  when: win_services is defined and win_services
  tags:
    - services
  block:
    - name: Disable unnecessary services
      ansible.windows.win_service:
        name: "{{ item }}"
        start_mode: disabled
        state: stopped
      with_items: "{{ ansible.windows.win_services_disable }}"
      failed_when: false

    - name: Set some services in manual start
      ansible.windows.win_service:
        name: "{{ item }}"
        start_mode: manual
      with_items: "{{ ansible.windows.win_services_manual }}"
      failed_when: false

    - name: Set some services in automatic start
      ansible.windows.win_service:
        name: "{{ item }}"
        start_mode: auto
      with_items: "{{ ansible.windows.win_services_automatic }}"
      failed_when: false
