---

- name: Services
  block:
    - name: Disable unnecessary services
      win_service:
        name: "{{ item }}"
        start_mode: disabled
        state: stopped
      with_items: "{{ win_services_disable }}"
      failed_when: false

    - name: Set some services in manual start
      win_service:
        name: "{{ item }}"
        start_mode: manual
      with_items: "{{ win_services_manual }}"
      failed_when: false

    - name: Set some services in automatic start
      win_service:
        name: "{{ item }}"
        start_mode: auto
      with_items: "{{ win_services_automatic }}"
      failed_when: false

  when: win_services is defined and win_services
  tags:
    - services
